#!/usr/bin/env bash
####################################################################################
# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
#  Copyright 2025 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##################################################################################
unset _RDK_FLAVOR

TOP_DIR=$(pwd)
export RDK_BSP_LAYER=none

BUILD_ALL_MACHINES=0
if [ -z "${MACHINE}" ]; then
	echo -e "The default machine for this layer is \"armefi64-rdk-broadband\""
	echo -e "To build for another machine, specify the MACHINE environment variable"
	echo -e "To build for all armefi64 machine types, specify MACHINE as \"all\""
	echo -e ""
elif [ "${MACHINE}" = "all" ]; then
	MACHINE="armefi64-rdk-broadband"
	BUILD_ALL_MACHINES="1"
fi

export MACHINE=${MACHINE:-armefi64-rdk-broadband}

source meta-cmf/setup-environment
if [ $? -ne 0 ]; then
    echo "setup-environment failed"
    return 1
fi

# at this point the current directory should be the build dir
BUILD_DIR=$(pwd)
echo "Build directory: ${BUILD_DIR}"
# replace RDK FLAVOR to set BBMASKS
sed -e "s|##RDK_FLAVOR##|${_RDK_FLAVOR}|g" -i $TOP_DIR/meta-rdk-bsp-arm/conf/layer.conf

if [ "${RDK_ENABLE_REFERENCE_IMAGE}" = "y" ]; then
    if [ $(grep conf/local.conf -c -e 'reference.inc') -eq 0 ]; then
        echo "require conf/distro/include/reference.inc" >>  conf/local.conf
        echo "export RDK_ENABLE_REFERENCE_IMAGE = \"y\"" >> conf/local.conf
    fi
fi

# Setup BitBake multi-build to build both the generic
# and derived machines (like the RaspberryPi) in the
# one build structure.
# You can then use
# "bitbake mc:generic:rdk-generic-broadband-image" and 
# "bitbake mc:raspberrypi:rdk-generic-broadband-image"
# to build each target.
if [ "${BUILD_ALL_MACHINES}" = "1" ]; then
	echo "Enabling multi-build for generic (QEMU firmware) and RaspberryPi 64-bit"
	mkdir -p conf/multiconfig
	echo -e 'MACHINE="armefi64-rdk-broadband"' > "conf/multiconfig/generic.conf"
	echo -e 'MACHINE="raspberrypi64-rdk-broadband"' > "conf/multiconfig/raspberrypi.conf"
	echo -e 'MACHINE="ten64-rdk-broadband"' > "conf/multiconfig/ten64.conf"
	echo -e 'MACHINE="armefi64-qemu-broadband"' > "conf/multiconfig/qemu.conf"
	echo -e 'BBMULTICONFIG="generic raspberrypi ten64"' >> "conf/local.conf"
fi
