DEVICE_TYPE=broadband
BUILD_TYPE=dev
MOCA_INTERFACE=eth0
ETHERNET_INTERFACE=eth0
BUILD_VERSION=
MANUFACTURE=
LOG_PATH=/rdklogs/logs/
CORE_PATH=/mnt/memory/corefiles/
PROCESS_RESTART_LOG=/dev/null
MESH_SUPPORTED=false
WAN_TYPE=DOCSIS
MOCA_SUPPORTED=false
DOCSIS_SUPPORTED=true
BRIDGE_MODE_SUPPORTED=true
DEVICE_ROUTER=false
BATTERY_SUPPORTED=true
WPS_SUPPORTED=true
VOICE_SUPPORTED=true
WAN0_IS_DUMMY=false
WanFailOverSupportEnable=true
BOX_TYPE=genericarm
MODEL_NAME=GENERICARM
MODEL_NUM=RPI_MOD
PARODUS_URL=tcp://127.0.0.1:6666
WEBPA_CLIENT_URL=tcp://192.168.101.3:6667
SERVERURL=https://webpa.rdkcentral.com:8080
